version: "3.3"

services:
  db:
    image: postgres:10.10-alpine
    environment:
      POSTGRES_USER: jdisctf
      POSTGRES_PASSWORD: jdisctf
      POSTGRES_DB: jdisctf_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  frontend-user:
    build: ./frontend/user
    image: frontend-user

  frontend-admin:
    build: ./frontend/admin
    image: frontend-admin

  backend:
    build: ./backend
    restart: always
    depends_on:
      - db

  nginx:
    build: ./nginx
    cap_add:
      - NET_ADMIN
    # Set this if you want to use HTTPS with lets encrypt. If so, simply put the domain name at which Flaggr will be accessible (example mydomain.org)
    #environment:
    #  - DOMAIN=res260.xyz

    depends_on:
      - backend
      - frontend-user
      - frontend-admin

    volumes:
      - ./letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    restart: always
